# Generated by Django 5.1.6 on 2025-02-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=512)),
                ('image', models.ImageField(max_length=1024, upload_to='D:\\S. School\\MIT\\Machine Learning\\Assignment\\Assignment 2 - FLASKDJANGO implementation of Image Classification\\madi_image_classifier_api\\media\\dataset\\temp/uploads')),
            ],
            options={
                'db_table': 'uploaded_images',
            },
        ),
    ]
